### ISSUE TITLE
Bootloader locked !

### ISSUE THREAD

**Issue by scafroglia93** [meizuosc/m681-intl#1]
How do I install the kernel if the smartphone is locked bootloader?

**Comment by wengpingbo** [comment]
No, you can't. Meizu has opened their bootloader in international series phone only.

**Comment by scafroglia93** [comment]
Are you sure ? Some M3 Note users with G firmware they told me that the boot is lock without any way to unlock

Edit: You release kernel source with lock bootloader ? It's very very strange

I'm wait a response

**Comment by rentocika** [comment]
I'm have M681H with 5.1.3.3G and bootloader is locked. Why you share this sources for M3 Note with locked bootloader???

**Comment by scafroglia93** [comment]
@ShaihutdinovRZ This is the problem

**Comment by scafroglia93** [comment]
@wengpingbo Any response from Meizu about this problem ?

**Comment by scafroglia93** [comment]
@meizuosc I need response please

**Comment by scafroglia93** [comment]
?????????????????????????????????????????????????????????

**Comment by ghost** [comment]
@wengpingbo Giving us some help to unlock the bootloader would be nice, otherwise this kernel release doesn't give us much useful use.

**Comment by scafroglia93** [comment]
No reply from meizu

**Comment by ghost** [comment]
So most likely will continue to stay locked? @scafroglia93

**Comment by tversteeg** [comment]
I'm guessing the only reason why they share the source is because the GPL license of the kernel is forcing them to.

**Comment by scafroglia93** [comment]
Meizu where are you ?

**Comment by LiXiao-Py** [comment]
Yes, and I'm gaged to say anything about locking bootloader at meizu bbs. 呵呵哒，还禁言我，锁着bootloader，放出源码有设么用？？？现在还在用Android5.1，友商都上7.0了.

**Comment by lanlanpy** [comment]
now ,the bootloader is unlock

**Comment by lanlanpy** [comment]
i am build this source and can boot the android 5.1

**Comment by scafroglia93** [comment]
LOL

**Comment by lanlanpy** [comment]
but i am not able to build rom😂😂😂

**Comment by tversteeg** [comment]
Where to find the bootloader?

**Comment by tversteeg** [comment]
Where to find the bootloader?

**Comment by Akshadv48** [comment]
any one knows how to unlock bootloader of meizu m3 n l618
